global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'airflow-local'
    metrics_path: /admin/metrics
    static_configs:
      - targets:
          - localhost:8080